# Generated by Django 4.2.16 on 2024-09-20 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowingtransaction",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="borrowingtransaction",
            unique_together={("borrower", "book")},
        ),
    ]
