# Generated by Django 4.2.16 on 2024-09-20 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_borrowingtransaction_borrower_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowedbook",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.book"
            ),
        ),
    ]
