# Generated by Django 4.2.16 on 2024-09-21 00:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_borrowedbook_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="is_reserved",
            new_name="reserved",
        ),
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
    ]
