# Generated by Django 4.2.16 on 2024-09-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_is_reserved_book_reserved_remove_book_isbn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="reserved",
        ),
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="book_images/"),
        ),
        migrations.AddField(
            model_name="book",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
